# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\py_project\TelegramIOS-control\UI\settings_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingUI(object):
    def setupUi(self, SettingUI):
        SettingUI.setObjectName("SettingUI")
        SettingUI.resize(1034, 713)
        self.retranslateUi(SettingUI)
        QtCore.QMetaObject.connectSlotsByName(SettingUI)

    def retranslateUi(self, SettingUI):
        _translate = QtCore.QCoreApplication.translate
        SettingUI.setWindowTitle(_translate("SettingUI", "ScrollArea"))
    