# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\py_project\TelegramIOS-control\UI\settingsInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsInterface(object):
    def setupUi(self, SettingsInterface):
        SettingsInterface.setObjectName("SettingsInterface")
        SettingsInterface.resize(710, 592)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsInterface.sizePolicy().hasHeightForWidth())
        SettingsInterface.setSizePolicy(sizePolicy)
        SettingsInterface.setWindowTitle("")
        self.gridLayout_3 = QtWidgets.QGridLayout(SettingsInterface)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.settingsSmoothScrollArea = SmoothScrollArea(SettingsInterface)
        self.settingsSmoothScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settingsSmoothScrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.settingsSmoothScrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.settingsSmoothScrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.settingsSmoothScrollArea.setWidgetResizable(True)
        self.settingsSmoothScrollArea.setObjectName("settingsSmoothScrollArea")
        self.settingsScrollAreaWidgetContents = QtWidgets.QWidget()
        self.settingsScrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 676, 532))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsScrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.settingsScrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.settingsScrollAreaWidgetContents.setObjectName("settingsScrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settingsScrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.settingsSmoothScrollArea.setWidget(self.settingsScrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.settingsSmoothScrollArea, 2, 1, 1, 1)

        self.retranslateUi(SettingsInterface)
        QtCore.QMetaObject.connectSlotsByName(SettingsInterface)

    def retranslateUi(self, SettingsInterface):
        pass
from qfluentwidgets import SmoothScrollArea
